# Advent of Code 2024
## Day 09


### Part 1

In [276]:
import copy

filename = 'input.txt'
filename = 'test_input.txt'

with open( filename ) as file:
    data = file.read()

files = [ int(x) for x in data[0::2] ]
free_blocks = [ int(x) for x in data[1::2] ]

total_files = sum( files ) 

file_dict = {}
data_number = 0
data_len = 0
for ii in range( len( files ) ):
    file_dict[ ii ] = [ data_number, int( files[ii] ), total_files+ii ]
    data_len += files[ii]
    data_number += 1
    
free_list = []
data_len = 0
for ii in range( 0, len( data ), 2 ):
    # print(ii)
    data_len += int( data[ii] )
    try:
        free_list.append( [ data_len, int( data[ii+1] ) ] )
        data_len += int( data[ii+1] )
    except IndexError:
        break
    
file_dict_og = copy.deepcopy( file_dict )
file_dict, free_blocks, total_files, free_list, free_blocks

({0: [0, 2, 28],
  1: [1, 3, 29],
  2: [2, 1, 30],
  3: [3, 3, 31],
  4: [4, 2, 32],
  5: [5, 4, 33],
  6: [6, 4, 34],
  7: [7, 3, 35],
  8: [8, 4, 36],
  9: [9, 2, 37]},
 [3, 3, 3, 1, 1, 1, 1, 1, 0],
 28,
 [[2, 3],
  [8, 3],
  [12, 3],
  [18, 1],
  [21, 1],
  [26, 1],
  [31, 1],
  [35, 1],
  [40, 0]],
 [3, 3, 3, 1, 1, 1, 1, 1, 0])

In [277]:
import numpy as np

# new_file_system = []
# ans = 0
# prev_start = 0
# free_ind = 0
# file_ind = 0
# file_end_ind = len( file_dict ) - 1
# block_end = 0

    
# while True:

#     file_num, file_length, _ = file_dict[ file_ind ]
#     # print( file_num, file_length )

#     block_end = prev_start + file_length
#     # print( file_length )

#     coefficients = np.arange( prev_start, block_end )
#     files = file_num*np.ones( file_length )

#     ans += sum( coefficients * files )
    
#     if block_end >= total_files:
#         break
    
#     prev_start = block_end
#     file_ind += 1
#     free_length = free_blocks[ free_ind ]
#     if free_length > 0:
#         while free_length > 0:
        
        
#             file_num, file_length, _ = file_dict[ file_end_ind ] 
            
#             if free_length == file_length:
#                 block_end = prev_start + file_length
                
#                 coefficients = np.arange( prev_start, block_end )
#                 files = file_num*np.ones( file_length )
#                 ans += sum( coefficients * files )
                
#                 free_blocks[ free_ind ] = 0
#                 prev_start = block_end
#                 file_end_ind -= 1
#                 free_ind += 1
#                 free_length -= file_length
                
#             elif free_length > file_length:
#                 block_end = prev_start + file_length
                
#                 coefficients = np.arange( prev_start, block_end )
#                 files = file_num*np.ones( file_length )
#                 ans += sum( coefficients * files )
            
#                 prev_start = block_end
#                 free_blocks[ free_ind ] -= file_length
#                 free_length -= file_length
#                 if free_blocks[ free_ind ] < 1:
#                     free_ind += 1
#                 file_end_ind -= 1
#             else:
#                 block_end = prev_start + free_length
                
#                 coefficients = np.arange( prev_start, block_end )
#                 files = file_num*np.ones( free_length )
#                 ans += sum( coefficients * files )
                
#                 free_blocks[ free_ind ] = 0
#                 prev_start = block_end
#                 file_dict[ file_end_ind ][1] -= free_length
#                 free_length -= file_length
#                 if file_dict[ file_ind ][1] < 1:
#                     file_end_ind += 1
#                 free_ind += 1
            
#         if block_end >= total_files:
#             break
#     else:
#         free_ind += 1
    

# print( int(ans) )

### Part 2

In [278]:
file_dict = copy.deepcopy( file_dict_og )

asd = []
asdf = 0
for ii in data:
    asd.append( asdf )
    asdf += int(ii)

temp = 0
for ii, key in enumerate( file_dict.keys() ):
    file_dict[ key ][2] = asd[temp]
    temp += 2

free_ind = 0
new_filesystem = []
    
for key in list( file_dict.keys() )[ ::-1 ]:
    file_num, file_len, file_start = file_dict[key]
    while True:
        free_start, free_len = free_list[ free_ind ]
        
        if file_len == free_len and free_start < file_start:
            
            new_entry = [ file_start, file_len ]
           
            free_list.append( new_entry )
            free_list.sort( key=lambda x: x[0] )
            
            file_dict[ key ][2] = free_start
            free_list.pop( free_ind )
        
            new_filesystem.append( file_dict[ key ] )
            
            break
        
        elif file_len < free_len and free_start < file_start:
            
            new_entry = [ file_start, file_len ]
        
            free_list.append( new_entry )
            free_list.sort( key=lambda x: x[0] )
            # print( free_start )
            file_dict[ key ][2] = free_start
            new_filesystem.append( file_dict[ key ] )
            free_list[ free_ind ] = [ free_start + file_len, free_len - file_len ]
            
            break
            
        else:
            free_ind += 1
            if free_ind >= len( free_list ):
                free_ind = 0
                new_filesystem.append( file_dict[ key ] )
                break

for ii, elem in enumerate( free_list ):
    free_list[ii] = [ 0, elem[1], elem[0] ]
    
for ii, elem in enumerate( free_list ):
    if elem[1] == 0:
        free_list.pop( ii )

new_filesystem.extend( free_list )      
new_filesystem.sort( key=lambda x: x[2] )


In [ ]:
ans = 0
for entry in new_filesystem:
    num, length, prev_start = entry
    block_end = prev_start + length
        
    coefficients = np.arange( prev_start, block_end )
    files = num*np.ones( length )
    
    # print( coefficients, files)
    ans += sum( coefficients * files )
    
   
print( ans )    # 7886024298205

new_filesystem

[0 1] [0. 0.]
[2 3] [9. 9.]
[4] [2.]
[5 6 7] [1. 1. 1.]
[ 8  9 10] [7. 7. 7.]
[11] [0.]
[12 13] [4. 4.]
[14] [0.]
[15 16 17] [3. 3. 3.]
[18] [0.]
[19 20] [0. 0.]
[21] [0.]
[22 23 24 25] [5. 5. 5. 5.]
[26] [0.]
[27 28 29 30] [6. 6. 6. 6.]
[31] [0.]
[32 33 34] [0. 0. 0.]
[35] [0.]
[36 37 38 39] [8. 8. 8. 8.]
[40 41] [0. 0.]
2858.0


[[0, 2, 0],
 [9, 2, 2],
 [2, 1, 4],
 [1, 3, 5],
 [7, 3, 8],
 [0, 1, 11],
 [4, 2, 12],
 [0, 1, 14],
 [3, 3, 15],
 [0, 1, 18],
 [0, 2, 19],
 [0, 1, 21],
 [5, 4, 22],
 [0, 1, 26],
 [6, 4, 27],
 [0, 1, 31],
 [0, 3, 32],
 [0, 1, 35],
 [8, 4, 36],
 [0, 2, 40]]

The following block stays here as a monument of pain

In [280]:
# new_file_system = []
# ans = 0
# prev_start = 0
# free_ind = 0
# file_ind = 1
# file_end_ind = -1
# block_end = 0
# end_loops = False               
      
# file_dict = copy.deepcopy( file_dict_og )

# asd = []
# asdf = 0
# for ii in data:
#     asd.append( asdf )
#     asdf += int(ii)

# temp = 0
# for ii, key in enumerate( file_dict.keys() ):
#     file_dict[ key ][2] = asd[temp]
#     temp += 2
    
    
# file_dict[ 0 ][2] = 0
# while True:
#     if end_loops:
#         break
    
#     free_start, free_len = free_list[ free_ind ]
    
#     while True:
#         key = list( file_dict.keys() )[ file_end_ind ]
#         _, file_len, file_start = file_dict[ key ]
#         if free_len > 0:
#             if free_len == file_len and free_start < file_start:
                
                
#                 new_entry = [ file_start, file_len ]
#                 for ii in range( len( free_list ) - 1 ):
#                     check1 = False
#                     check2 = False
#                     ind, lent = free_list[ii]
#                     if file_dict[ key ][2] == ind + lent:
#                         # free_list[ii][] += file_len
#                         new_entry[0] = ind
#                         new_entry[1] += lent
#                         # free_list[ii][1] += file_len
#                         check1 = True

#                     try:
#                         ind = free_list[ii+1][0]
#                         if file_dict[ key ][2] + file_len == ind:
#                             new_entry[1] += free_list[ii+1][1]
#                             check2 = True
                          
#                     except IndexError:
#                         pass
                    
#                     if check1 and check2:
#                         free_list.pop( ii )
#                         free_list.pop( ii ) 
#                         break
#                     elif check1:
#                         free_list.pop( ii ) 
#                         break
#                     elif check2:
#                         free_list.pop( ii+1 ) 
#                         break
                        
#                 free_list.append( new_entry )
#                 free_list.sort( key=lambda x: x[0] )
                        
                      
#                 file_dict[ key ][2] = free_start
#                 free_list.pop( free_ind )
                
#                 file_dict = dict( sorted( file_dict.items(), key=lambda item: item[1][2], reverse=False ) )

#                 free_ind = 0
#                 file_end_ind = list( file_dict.keys() )[-1]
                
#                 if len( free_list ) == 0:
#                     end_loops = True
                    
#                 break
                          
#             elif free_len > file_len and free_start < file_start:
                
#                 new_entry = [ file_start, file_len ]
#                 for ii in range( len( free_list ) - 1 ):
#                     check1 = False
#                     check2 = False
#                     ind, lent = free_list[ii]
#                     if file_dict[ key ][2] == ind + lent:
#                         # free_list[ii][] += file_len
#                         new_entry[0] = ind
#                         new_entry[1] += lent
#                         # free_list[ii][1] += file_len
#                         check1 = True

#                     try:
#                         ind = free_list[ii+1][0]
#                         if file_dict[ key ][2] + file_len == ind:
#                             new_entry[1] += free_list[ii+1][1]
#                             check2 = True
                          
#                     except IndexError:
#                         pass
                    
#                     if check1 and check2:
#                         free_list.pop( ii )
#                         free_list.pop( ii ) 
#                         break
#                     elif check1:
#                         free_list.pop( ii ) 
#                         break
#                     elif check2:
#                         free_list.pop( ii+1 ) 
#                         break
                        
#                 free_list.append( new_entry )
#                 free_list.sort( key=lambda x: x[0] )
                
                
                    
#                 file_dict[ key ][2] = free_start
#                 free_list[ free_ind ] = [ free_start + file_len, free_len - file_len ]
                
#                 file_dict = dict( sorted( file_dict.items(), key=lambda item: item[1][2], reverse=False ) )
                
#                 free_len -= file_len
#                 file_end_ind = -1
                
#                 if len( free_list ) == 0:
#                     end_loops = True
#                     break
                
#             else:
#                 free_ind += 1
                
#                 if free_ind >= len( free_list ):
#                     free_ind = 0
#                     file_end_ind -= 1
                    
#                     end_key = list( file_dict.keys() )[ file_end_ind ]
#                     if file_dict[ end_key ][2] == 0:
#                         end_loops = True
                    
#                     break
#                 else:
#                     free_start, free_len = free_list[ free_ind ]
#         else:
#             free_ind += 1
#             try:
#                 free_start, free_len = free_list[ free_ind ]
#             except IndexError:
#                 free_list.pop( free_ind-1 )
#                 free_ind = 0
#                 file_end_ind = -1
#                 break
                

# ans = 0
# for key in file_dict.keys():
#     num, length, prev_start = file_dict[key] 
#     block_end = prev_start + length
        
#     coefficients = np.arange( prev_start, block_end )
#     files = num*np.ones( length )
    
#     # print( coefficients, files )
#     # prrr = input("asd: ")
#     ans += sum( coefficients * files )
   
# print( ans )
# file_dict, free_list